# Generated by Django 4.2.11 on 2024-05-14 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('status', models.SmallIntegerField(default=9)),
                ('product', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.SmallIntegerField(default=9)),
                ('repository', models.CharField(max_length=250)),
                ('main_branch', models.CharField(max_length=250)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.build')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ComponentChange',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('target_branch', models.CharField(max_length=250)),
                ('source_branch', models.CharField(max_length=250)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.component')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('status', models.SmallIntegerField(default=9)),
                ('description', models.TextField(blank=True)),
                ('last_update_date', models.DateTimeField(auto_now=True)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.build')),
                ('last_update_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=250)),
                ('component', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='features.component')),
                ('component_change', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='features.componentchange')),
                ('feature', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='features.feature')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='componentchange',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.feature'),
        ),
        migrations.CreateModel(
            name='PropertyTemplate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('COMPONENT', 'component'), ('FEATURE', 'feature')], max_length=100, null=True)),
                ('name', models.CharField(max_length=250)),
                ('values', models.CharField(max_length=500)),
                ('status', models.SmallIntegerField(default=9)),
                ('build', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='features.build')),
            ],
            options={
                'ordering': ['-id'],
                'unique_together': {('build', 'name')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='componentchange',
            unique_together={('feature', 'component')},
        ),
    ]
