# Generated by Django 4.2.11 on 2024-06-24 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='style',
            field=models.CharField(default='widget:text;read_only:false;hidden:false;', max_length=250),
        ),
        migrations.AddField(
            model_name='propertytemplate',
            name='style',
            field=models.CharField(default='widget:text;read_only:false;hidden:false;', max_length=250),
        ),
        migrations.AlterField(
            model_name='property',
            name='value',
            field=models.CharField(max_length=500),
        ),
    ]
